//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemoApi.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JapaneseWordEntry
    {
        public long EntryId { get; set; }
        public string Hiragana { get; set; }
        public string Romaji { get; set; }
        public string Kanji { get; set; }
        public string AdditionalText { get; set; }
        public string MotherTongueTranslation { get; set; }
        public string MotherTongueTranslationLabel { get; set; }
    }
}
